services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env
    depends_on:
      - postgres
      - mongo
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend/threat-detection
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  mongo_data:
